### ISSUE TITLE
 Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by Whuhxh** [Chatie/webwx-app-tracker#3]
@zixia, I think this is a bug when I first start the bot, you may consider the "undefined" situation of load of a contact by the contact id.
ERR Room contactGetter(@@c4f424080c5f480442dfb0dd5af062b70443edf95c9d1b87c1e15ab1b212fe24) exception: Cannot read property 'Symbol(Symbol.iterator)' of undefined
ERR Message ready() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Room.<anonymous> (/bot/node_modules/wechaty/dist/src/room.js:52:32)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/room.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
    at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
    at Room.<anonymous> (/bot/node_modules/wechaty/dist/src/room.js:88:28)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERR PuppetWebEvent onServerMessage() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Room.<anonymous> (/bot/node_modules/wechaty/dist/src/room.js:52:32)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/room.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
    at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
    at Room.<anonymous> (/bot/node_modules/wechaty/dist/src/room.js:88:28)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERR Config ###########################
ERR Config unhandledRejection: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined [object Promise]
ERR Config ###########################
ERR Config unhandledRejection::catch(Cannot read property 'Symbol(Symbol.iterator)' of undefined)
(node:27) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
ERR Room contactGetter(@@c4f424080c5f480442dfb0dd5af062b70443edf95c9d1b87c1e15ab1b212fe24) exception: Cannot read property 'Symbol(Symbol.iterator)' of undefined
ERR Message ready() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Room.<anonymous> (/bot/node_modules/wechaty/dist/src/room.js:52:32)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/room.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
    at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
    at Room.<anonymous> (/bot/node_modules/wechaty/dist/src/room.js:88:28)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERR PuppetWebEvent onServerMessage() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Room.<anonymous> (/bot/node_modules/wechaty/dist/src/room.js:52:32)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/room.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
    at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
    at Room.<anonymous> (/bot/node_modules/wechaty/dist/src/room.js:88:28)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERR Config ###########################
ERR Config unhandledRejection: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined [object Promise]
ERR Config ###########################
ERR Config unhandledRejection::catch(Cannot read property 'Symbol(Symbol.iterator)' of undefined)
(node:27) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)

**Comment by huan** [comment]
Hi, 

Here is not the right place to discuss Wechaty.

Please post to https://github.com/wechaty/wechaty/issues and follow the TEMPLATE.

Thanks.
